"""
11_dspy_extra_content.py — DSPy evaluation for Hypothesis 1: extra-content classification

Purpose:
    Evaluate whether a small language model, prompted via DSPy, can correctly classify
    the semantic role of extra content in subset place-name conflicts — the specific gap
    that rules cannot fill (see README § ML Extension Hypotheses, Hypothesis 1).

    This is the primary SLM experiment for the paper. The hypothesis:
        A ChainOfThought module over a 4-class classifier, optimized with
        BootstrapFewShot, achieves ≥85% accuracy on held-out subset conflict rows
        where rule-based selection is uncertain.

Input:
    analysis/names/name_hard_cases_eval_autogenerated.csv   — 304 labeled hard cases (305 descriptor
                                                 + parenthetical, latin-script only)
    Columns used: short_name, long_name, extra_content, script_type, correct_answer

Output:
    analysis/names/dspy_h1_results.csv        — per-row predictions with correctness flag
    analysis/names/dspy_h1_summary.csv        — accuracy by class and overall

Classification taxonomy:
    business_type   Extra describes WHAT the place IS (Hotel, Supermarket, Dance Studio).
                    → Prefer longer name.
    location        Extra is a place name: city, state, country, neighborhood, street.
                    → Prefer shorter name (usually).
    disambiguation  Extra identifies a branch, owner, service list, or affiliation.
                    → Prefer shorter unless core name is non-viable alone.
    noise           Extra is listing boilerplate: credentials, legal numbers, SEO keywords,
                    marketing taglines, owner notations.
                    → Always prefer shorter name.

Usage:
    # Default: run with claude-haiku-4-5 (cheapest viable model to test first)
    python 11_dspy_extra_content.py

    # Specify a different LM:
    python 11_dspy_extra_content.py --model claude-sonnet-4-6

    # Use OpenAI:
    python 11_dspy_extra_content.py --provider openai --model gpt-4o-mini

    # Run optimizer (BootstrapFewShot) and save optimized program:
    python 11_dspy_extra_content.py --optimize --save-path optimized/h1_bootstrap.json

    # Evaluate a saved optimized program:
    python 11_dspy_extra_content.py --load-path optimized/h1_bootstrap.json

Dependencies:
    pip install dspy-ai anthropic pandas
"""

import argparse
import json
import os
import sys
from pathlib import Path

import pandas as pd

# Load .env from the project root (one level up from scripts/)
try:
    from dotenv import load_dotenv
    load_dotenv(Path(__file__).parent.parent / ".env")
except ImportError:
    pass  # python-dotenv optional; fall back to shell environment

try:
    import dspy
except ImportError:
    sys.exit("dspy-ai is required: pip install dspy-ai")


# ── Paths ──────────────────────────────────────────────────────────────────────

EVAL_PATH    = "../analysis/names/name_hard_cases_eval.csv"
RESULTS_PATH = "../analysis/names/dspy_h1_results.csv"
SUMMARY_PATH = "../analysis/names/dspy_h1_summary.csv"

VALID_CLASSES = {"business_type", "location", "disambiguation", "noise"}

TRAIN_FRAC = 0.6   # 60% train (used for few-shot bootstrap), 40% held-out eval
RANDOM_SEED = 42


# ══════════════════════════════════════════════════════════════════════════════
#  DSPy SIGNATURE
# ══════════════════════════════════════════════════════════════════════════════

class ExtraContentClassifier(dspy.Signature):
    """
    Classify the semantic role of extra content in a place name subset conflict.

    Context: One place name is entirely contained within another. The longer name adds
    "extra content" beyond the shorter core name. Your job is to classify what that
    extra content IS — this determines whether to keep the longer or shorter name.

    Four classes:
    - business_type: The extra content describes what KIND of place this is.
      Examples: "Hotel", "Supermarket", "Dance Studio", "Dental Clinic", "Pharmacy",
      "Restaurant", "Fachmarkt für Heizung & Sanitär" (German plumbing supply store),
      "Sachverständige für Immobilien" (certified real estate appraiser).
      Rule: if you know what the place IS from the extra content, it's business_type.
      → Select the LONGER name (the business type adds essential information).

    - location: The extra content is a place name — city, neighborhood, state, country,
      street, or geographic qualifier.
      Examples: "Champs-Elysées", "Florida", "Hammersmith", "Canada", "Marseille",
      "Nashville Tennessee West", "Rancho Cucamonga CA", "Florissant".
      Note: a location that also disambiguates (Kip McGrath Hammersmith — the only Kip
      McGrath in Hammersmith) is still classified as location.
      → Select the SHORTER name (the location qualifier is usually directory noise).

    - disambiguation: The extra content identifies a specific branch, owner, service list,
      organizational affiliation, or franchise/parallel brand — without being a place name
      or a business type.
      Examples: "State Farm Insurance Agent", "at Guaranteed Rate Affinity", "Franchisé
      indépendant", "Coldwell Banker Commercial Schmidt", "| Webentwicklung & IT-Infrastruktur",
      "/ Godfather's Pizza Express", "Senior Care", "Financial Advisor: Heidi Lue".
      → Select the SHORTER name (the core name is the canonical form).

    - noise: The extra content is listing boilerplate that adds no semantic value — license
      numbers, professional credentials appended to a personal name, legal ownership
      notations, marketing taglines, online-channel descriptors, or vintage/batch identifiers.
      Examples: "NMLS #344084", "M.D.", "Inh. Harald H. J. Mählenhoff e.K.",
      "Uno dei Borghi più Belli d'Italia", "Shop Online Prodotti Vegani",
      "Small Batch Revival 2011", "S.C." (Mexican Sociedad Civil), "Co." (Company).
      → Select the SHORTER name (always).
    """

    short_name: str = dspy.InputField(
        desc="The shorter, core place name (the one that is contained within the longer name)"
    )
    long_name: str = dspy.InputField(
        desc="The longer place name that contains the core name plus extra content"
    )
    extra_content: str = dspy.InputField(
        desc=(
            "The normalized extra content — what the longer name adds beyond the shorter name. "
            "Already lowercased and punctuation-stripped for comparison."
        )
    )
    script_type: str = dspy.InputField(
        desc="Script family of the names: 'latin', 'cjk', or 'thai'"
    )

    classification: str = dspy.OutputField(
        desc="One of exactly: business_type, location, disambiguation, noise"
    )
    confidence: str = dspy.OutputField(
        desc="One of exactly: high, medium, low"
    )
    reasoning: str = dspy.OutputField(
        desc=(
            "One sentence explaining why this classification was chosen. "
            "Be specific about which word or phrase in extra_content drove the decision."
        )
    )


# ══════════════════════════════════════════════════════════════════════════════
#  MODULE
# ══════════════════════════════════════════════════════════════════════════════

class ExtraContentModule(dspy.Module):
    """
    ChainOfThought wrapper around ExtraContentClassifier.

    ChainOfThought causes the model to reason step-by-step before producing the
    final output fields — empirically improves accuracy on multi-class classification
    tasks compared to Predict (direct answer) for this kind of semantic judgment.
    """

    def __init__(self):
        super().__init__()
        self.classify = dspy.ChainOfThought(ExtraContentClassifier)

    def forward(self, short_name: str, long_name: str, extra_content: str, script_type: str):
        pred = self.classify(
            short_name=short_name,
            long_name=long_name,
            extra_content=extra_content,
            script_type=script_type,
        )
        # Normalize classification to one of the four valid classes
        cls = pred.classification.strip().lower().replace(" ", "_").replace("-", "_")
        if cls not in VALID_CLASSES:
            # Fuzzy fallback: take the first valid class that appears in the output
            for valid in VALID_CLASSES:
                if valid in cls:
                    cls = valid
                    break
            else:
                cls = "disambiguation"  # safe default
        pred.classification = cls
        return pred


# ══════════════════════════════════════════════════════════════════════════════
#  METRIC
# ══════════════════════════════════════════════════════════════════════════════

def exact_match(example, pred, trace=None):
    """Binary metric: 1 if classification matches correct_answer, 0 otherwise."""
    return int(pred.classification == example.correct_answer)


# ══════════════════════════════════════════════════════════════════════════════
#  DATA LOADING
# ══════════════════════════════════════════════════════════════════════════════

def load_examples(path: str) -> list[dspy.Example]:
    df = pd.read_csv(path)
    # Drop rows with missing required fields
    df = df.dropna(subset=["short_name", "long_name", "extra_content", "correct_answer"])
    # Validate labels
    df = df[df["correct_answer"].isin(VALID_CLASSES)]
    examples = []
    for _, row in df.iterrows():
        ex = dspy.Example(
            short_name=str(row["short_name"]),
            long_name=str(row["long_name"]),
            extra_content=str(row["extra_content"]),
            script_type=str(row.get("script_type", "latin")),
            correct_answer=str(row["correct_answer"]),
        ).with_inputs("short_name", "long_name", "extra_content", "script_type")
        examples.append(ex)
    return examples


def train_test_split(examples: list, train_frac: float, seed: int):
    import random
    rng = random.Random(seed)
    shuffled = list(examples)
    rng.shuffle(shuffled)
    split = int(len(shuffled) * train_frac)
    return shuffled[:split], shuffled[split:]


# ══════════════════════════════════════════════════════════════════════════════
#  EVALUATION
# ══════════════════════════════════════════════════════════════════════════════

def run_evaluation(module: dspy.Module, examples: list[dspy.Example]) -> pd.DataFrame:
    import time
    rows = []
    t_start = time.time()
    for ex in examples:
        t_row_start = time.time()
        try:
            pred = module(
                short_name=ex.short_name,
                long_name=ex.long_name,
                extra_content=ex.extra_content,
                script_type=ex.script_type,
            )
            rows.append({
                "short_name":     ex.short_name,
                "long_name":      ex.long_name,
                "extra_content":  ex.extra_content,
                "script_type":    ex.script_type,
                "correct_answer": ex.correct_answer,
                "predicted":      pred.classification,
                "confidence":     getattr(pred, "confidence", ""),
                "reasoning":      getattr(pred, "reasoning", ""),
                "correct":        int(pred.classification == ex.correct_answer),
                "latency_s":      round(time.time() - t_row_start, 2),
            })
        except Exception as e:
            rows.append({
                "short_name":     ex.short_name,
                "long_name":      ex.long_name,
                "extra_content":  ex.extra_content,
                "script_type":    ex.script_type,
                "correct_answer": ex.correct_answer,
                "predicted":      "error",
                "confidence":     "",
                "reasoning":      str(e),
                "correct":        0,
                "latency_s":      round(time.time() - t_row_start, 2),
            })
    total_time = time.time() - t_start
    n = len(rows)
    print(f"\nThroughput: {n} rows in {total_time:.1f}s "
          f"({n/total_time*60:.1f} rows/min, {n/total_time*3600:.0f} rows/hr)")
    print(f"Avg latency per row: {total_time/n:.2f}s  |  "
          f"Min: {min(r['latency_s'] for r in rows):.2f}s  |  "
          f"Max: {max(r['latency_s'] for r in rows):.2f}s")
    return pd.DataFrame(rows)


def print_summary(results: pd.DataFrame) -> pd.DataFrame:
    overall = results["correct"].mean()
    print(f"\nOverall accuracy: {overall:.1%}  ({results['correct'].sum()} / {len(results)})")
    print()

    # Per-class breakdown
    summary_rows = []
    for cls in sorted(VALID_CLASSES):
        subset = results[results["correct_answer"] == cls]
        if len(subset) == 0:
            continue
        acc = subset["correct"].mean()
        n   = len(subset)
        print(f"  {cls:<18}  n={n:>3}  accuracy={acc:.1%}")
        summary_rows.append({"class": cls, "n": n, "accuracy": acc})

    # Confusion matrix
    print("\nConfusion matrix (rows=correct, cols=predicted):")
    classes = sorted(VALID_CLASSES)
    cm = pd.crosstab(
        results["correct_answer"], results["predicted"],
        rownames=["actual"], colnames=["predicted"]
    ).reindex(index=classes, columns=classes, fill_value=0)
    print(cm.to_string())

    return pd.DataFrame(summary_rows)


# ══════════════════════════════════════════════════════════════════════════════
#  LM SETUP
# ══════════════════════════════════════════════════════════════════════════════

def configure_lm(provider: str, model: str):
    """
    Configure the DSPy language model.

    Provider/model combinations for this project:

    BASELINE (API, establishes accuracy ceiling):
        --provider anthropic --model claude-haiku-4-5-20251001
        Requires: ANTHROPIC_API_KEY in .env

    TRUE SLM via local Ollama (free, no API cost, runs on CPU/GPU):
        --provider ollama --model mistral          # Mistral-7B
        --provider ollama --model llama3.1         # Llama-3.1-8B
        Setup: brew install ollama && ollama pull mistral
        No key needed.

    TRUE SLM via Together AI API (cheap, ~$0.20/1M tokens):
        --provider together --model mistralai/Mistral-7B-Instruct-v0.2
        Requires: TOGETHER_API_KEY in .env

    TRUE SLM via Groq (free tier, rate-limited):
        --provider groq --model llama-3.1-8b-instant
        Requires: GROQ_API_KEY in .env
    """
    if provider == "anthropic":
        lm = dspy.LM(f"anthropic/{model}")
    elif provider == "openai":
        lm = dspy.LM(f"openai/{model}")
    elif provider == "ollama":
        # Local inference via Ollama — no API key needed
        # DSPy uses LiteLLM under the hood; Ollama runs at localhost:11434
        lm = dspy.LM(f"ollama_chat/{model}", api_base="http://localhost:11434")
    elif provider == "together":
        lm = dspy.LM(f"together_ai/{model}")
    elif provider == "groq":
        lm = dspy.LM(f"groq/{model}")
    else:
        lm = dspy.LM(model)
    dspy.configure(lm=lm)
    print(f"LM configured: {provider}/{model}")


# ══════════════════════════════════════════════════════════════════════════════
#  MAIN
# ══════════════════════════════════════════════════════════════════════════════

def main():
    parser = argparse.ArgumentParser(description="DSPy Hypothesis 1 — extra-content classification")
    parser.add_argument("--provider",   default="ollama",              help="LM provider: ollama|anthropic|together|groq|openai")
    parser.add_argument("--model",      default="mistral",              help="Model name (default: mistral via Ollama)")
    parser.add_argument("--optimize",   action="store_true",            help="Run BootstrapFewShot optimizer")
    parser.add_argument("--save-path",  default=None,                   help="Path to save optimized program JSON")
    parser.add_argument("--load-path",  default=None,                   help="Path to load saved program JSON")
    parser.add_argument("--max-train",  type=int, default=None,         help="Cap training set size (for cost control)")
    parser.add_argument("--eval-path",  default=EVAL_PATH,              help="Path to evaluation CSV")
    args = parser.parse_args()

    # ── Configure LM ─────────────────────────────────────────────────────────
    configure_lm(args.provider, args.model)

    # ── Load data ─────────────────────────────────────────────────────────────
    print(f"Loading eval set from: {args.eval_path}")
    examples = load_examples(args.eval_path)
    print(f"Loaded {len(examples)} valid examples")
    print(f"Class distribution: {pd.Series([e.correct_answer for e in examples]).value_counts().to_dict()}")

    train_examples, eval_examples = train_test_split(examples, TRAIN_FRAC, RANDOM_SEED)
    if args.max_train:
        train_examples = train_examples[:args.max_train]
    print(f"Train: {len(train_examples)}  |  Eval: {len(eval_examples)}")

    # ── Build or load module ───────────────────────────────────────────────────
    module = ExtraContentModule()

    if args.load_path:
        print(f"Loading optimized program from: {args.load_path}")
        module.load(args.load_path)
    elif args.optimize:
        print("Running BootstrapFewShot optimizer...")
        from dspy.teleprompt import BootstrapFewShot
        optimizer = BootstrapFewShot(
            metric=exact_match,
            max_bootstrapped_demos=4,
            max_labeled_demos=4,
        )
        module = optimizer.compile(module, trainset=train_examples)
        if args.save_path:
            Path(args.save_path).parent.mkdir(parents=True, exist_ok=True)
            module.save(args.save_path)
            print(f"Saved optimized program to: {args.save_path}")

    # ── Evaluate ───────────────────────────────────────────────────────────────
    print(f"\nEvaluating on {len(eval_examples)} held-out examples...")
    results = run_evaluation(module, eval_examples)
    summary = print_summary(results)

    # ── Save outputs ───────────────────────────────────────────────────────────
    results.to_csv(RESULTS_PATH, index=False)
    summary.to_csv(SUMMARY_PATH, index=False)
    print(f"\nResults saved to: {RESULTS_PATH}")
    print(f"Summary saved to: {SUMMARY_PATH}")


if __name__ == "__main__":
    main()
