"""
11b_name_baselines.py — Non-SLM baseline comparisons for Hypothesis 1

Purpose:
    Train and evaluate three non-SLM baselines for extra-content classification,
    using the same 60/40 train/eval split as the DSPy evaluation (seed=42).
    Results are saved alongside the DSPy results for direct comparison.

    This script exists to make the paper's comparison reproducible. The baselines
    establish whether simpler (cheaper, faster) approaches can match the SLM, and
    to characterize exactly where they fall short.

Baselines:
    1. Majority class          — always predict the most common class (disambiguation)
    2. Rules — blind vocab     — keyword list from README §7 before any model feedback
    3. Rules — corrected vocab — same list after iterative correction from model review
    4. Word 1-2gram + LogReg   — TF-IDF on extra_content tokens, logistic regression
    5. Char 3-5gram + LogReg   — TF-IDF on character n-grams of extra_content

Inputs:
    analysis/names/name_hard_cases_eval_autogenerated.csv   — 304 labeled hard cases

Outputs:
    analysis/names/h1_baseline_comparison.csv         — accuracy table (all baselines)
    analysis/names/h1_all_approaches_comparison.csv   — per-row predictions, all methods
    analysis/names/h1_ngram_word_model.pkl            — saved word n-gram model
    analysis/names/h1_ngram_char_model.pkl            — saved char n-gram model

Key finding:
    Rules (corrected vocab) achieve ~96.7% SELECTION accuracy but require iterative
    manual construction — 21 vocabulary corrections derived from reviewing model outputs.
    N-gram classifiers trained on 182 examples perform WORSE than rules (70.5%/69.7%
    selection accuracy) because the training set is too small and city names are unseen.
    The SLM achieves 95.1% selection accuracy with zero vocabulary construction.

Why n-grams underperform:
    - 182 training examples across 4 classes is insufficient for reliable n-gram learning
    - The `location` class is dominated by proper nouns (city names, neighborhoods) that
      appear zero times in training: Queretaro, Azcapotzalco, Tromsø, Rockingham, etc.
    - N-gram models have no world knowledge; they can only match patterns seen in training
    - This is not a failure of n-grams generally — it is a dataset-size + vocabulary problem
"""

import pickle
import random
import re
from pathlib import Path

import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

# ── Paths ─────────────────────────────────────────────────────────────────────
ROOT        = Path(__file__).parent.parent
EVAL_PATH   = ROOT / "analysis/names/name_hard_cases_eval_autogenerated.csv"
COMPARE_OUT = ROOT / "analysis/names/h1_baseline_comparison.csv"
ROWS_OUT    = ROOT / "analysis/names/h1_all_approaches_comparison.csv"
WORD_MODEL  = ROOT / "analysis/names/h1_ngram_word_model.pkl"
CHAR_MODEL  = ROOT / "analysis/names/h1_ngram_char_model.pkl"

RANDOM_SEED = 42
TRAIN_FRAC  = 0.6
CLASSES     = ["business_type", "location", "disambiguation", "noise"]


# ── Vocabulary lists ──────────────────────────────────────────────────────────
# BIZ_BLIND: words explicitly in README §7 golden dataset rules before any
# iteration. This is the "fair" baseline — what a developer would write cold.
BIZ_BLIND = {
    "hotel", "motel", "inn", "resort", "lodge", "hostel", "suites",
    "bar", "pub", "tavern", "lounge", "brewery", "winery",
    "cafe", "bistro", "diner", "eatery", "canteen",
    "restaurant", "pizzeria", "steakhouse", "grill", "kitchen", "buffet", "deli",
    "bakery", "spa", "salon", "barbershop",
    "supermarket", "market", "mall", "plaza", "centre", "center",
    "hospital", "clinic", "pharmacy", "medical", "dental", "veterinary",
    "museum", "gallery", "theater", "cinema", "studio",
    "school", "university", "institute", "academy",
    "gym", "fitness", "bank", "insurance",
    "shop", "store", "boutique", "outlet",
    "orthodontist", "dentist", "agency", "agent", "advisor",
    "dance", "photography",
    # German
    "fachmarkt", "praxis", "therapien", "heizung", "technik",
    "immobilien", "sachverstandige",
}

# BIZ_FULL: BIZ_BLIND plus 21 words added after reviewing model outputs.
# Words the SLM identified correctly that the blind list missed — showing that
# a finite vocabulary always has gaps that world knowledge fills automatically.
BIZ_FULL = BIZ_BLIND | {
    # English gaps discovered via model review
    "church", "natatorium", "florists", "senior", "retirement", "apartments",
    "design", "transport", "care", "community", "arena", "photo", "lab",
    "propane", "chocolate", "bulbs", "prosthetics", "orthotics",
    # Non-English gaps — these required world knowledge to identify as business types
    "engenharia",         # Portuguese: engineering firm
    "estacionamento",     # Portuguese: parking lot
    "saude",              # Portuguese: health/wellness
    "terraza",            # Spanish: rooftop terrace/bar
    "lanches",            # Portuguese: snack bar
    "kirjasto",           # Finnish: library
    "vibrationstechnik",  # German: vibration technology (industrial specialty)
    "autofficina",        # Italian: auto repair shop
    "ankauf",             # German: buying (as in buy/sell shop)
    "verkauf",            # German: selling
    "sushi",              # Japanese cuisine type
    "acessorios",         # Portuguese: accessories store
    "bistrot", "ristorante", "trattoria",  # Italian restaurant types
}

NOISE_VOCAB = {
    "nmls", "facog", "md", "dds", "fnp", "inh", "ek",
    "llc", "inc", "corp", "ltd", "gmbh", "srl", "plc", "limited", "unlimited",
    "omg", "bba", "vip", "mcx", "vintage", "batch", "online", "internet", "borghi",
}


# ── Rule-based predictor ──────────────────────────────────────────────────────

def make_rule_predictor(biz_vocab: set):
    """
    Returns a function (row → predicted_class) using vocabulary rules + proper-noun
    location detection (uses capitalization in the original long_name).
    """
    def predict(row: pd.Series) -> str:
        ec = str(row["extra_content"]).lower()
        ln = str(row["long_name"])
        words = set(re.findall(r"\b\w+\b", ec))

        # 1. Noise: known boilerplate patterns
        if words & NOISE_VOCAB or re.search(r"#\d{3,}", ec):
            return "noise"

        # 2. Business type: vocabulary match
        if words & biz_vocab:
            return "business_type"

        # 3. Location: check if extra content words appear as capitalized proper nouns
        #    in the original long_name (title-case proper nouns in English/European names)
        ec_words = [w for w in re.findall(r"\b[a-z]+\b", ec) if len(w) > 2]
        if 1 <= len(ec_words) <= 4:
            cap_count = sum(
                1 for w in ec_words
                if re.search(r"\b" + re.escape(w[0].upper() + w[1:]) + r"\b", ln)
            )
            if len(ec_words) > 0 and cap_count / len(ec_words) >= 0.6:
                return "location"

        # 4. Default: disambiguation (can't determine from text alone)
        return "disambiguation"

    return predict


# ── Helpers ───────────────────────────────────────────────────────────────────

def selection_action(label: str) -> str:
    """Maps classification label to name selection decision."""
    return "keep_longer" if label == "business_type" else "keep_shorter"


def selection_accuracy(preds, truth) -> float:
    return sum(
        selection_action(p) == selection_action(t)
        for p, t in zip(preds, truth)
    ) / len(truth)


def per_class_accuracy(preds, truth) -> dict:
    preds = pd.Series(list(preds), index=truth.index)
    return {
        c: (preds[truth == c] == truth[truth == c]).mean()
        for c in CLASSES if (truth == c).sum() > 0
    }


# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    # Load data
    df = pd.read_csv(EVAL_PATH)

    # Reproduce the same train/eval split used in 11_dspy_extra_content.py
    rng = random.Random(RANDOM_SEED)
    indices = list(range(len(df)))
    rng.shuffle(indices)
    split = int(len(df) * TRAIN_FRAC)
    train = df.iloc[indices[:split]].reset_index(drop=True)
    test  = df.iloc[indices[split:]].reset_index(drop=True)

    X_train = train["extra_content"].fillna("")
    X_test  = test["extra_content"].fillna("")
    y_train = train["correct_answer"]
    y_test  = test["correct_answer"]

    print(f"Train: {len(train)} rows  |  Eval: {len(test)} rows")
    print(f"Eval class distribution: {y_test.value_counts().to_dict()}\n")

    # ── Baseline 0: majority class ─────────────────────────────────────────────
    majority = y_train.mode()[0]
    b0 = pd.Series([majority] * len(y_test), index=y_test.index)

    # ── Baselines 1 & 2: rule-based ────────────────────────────────────────────
    b1 = test.apply(make_rule_predictor(BIZ_BLIND), axis=1)
    b2 = test.apply(make_rule_predictor(BIZ_FULL),  axis=1)

    # ── Baseline 3: TF-IDF word 1-2gram + LogisticRegression ──────────────────
    vec_w = TfidfVectorizer(analyzer="word", ngram_range=(1, 2),
                            min_df=1, max_features=500)
    lr_w  = LogisticRegression(max_iter=1000, C=1.0,
                                class_weight="balanced", random_state=RANDOM_SEED)
    lr_w.fit(vec_w.fit_transform(X_train), y_train)
    b3 = pd.Series(lr_w.predict(vec_w.transform(X_test)), index=y_test.index)

    with open(WORD_MODEL, "wb") as f:
        pickle.dump({"vectorizer": vec_w, "classifier": lr_w}, f)

    # ── Baseline 4: TF-IDF char 3-5gram + LogisticRegression ──────────────────
    vec_c = TfidfVectorizer(analyzer="char_wb", ngram_range=(3, 5),
                            min_df=1, max_features=1000)
    lr_c  = LogisticRegression(max_iter=1000, C=1.0,
                                class_weight="balanced", random_state=RANDOM_SEED)
    lr_c.fit(vec_c.fit_transform(X_train), y_train)
    b4 = pd.Series(lr_c.predict(vec_c.transform(X_test)), index=y_test.index)

    with open(CHAR_MODEL, "wb") as f:
        pickle.dump({"vectorizer": vec_c, "classifier": lr_c}, f)

    # ── Summary table ──────────────────────────────────────────────────────────
    baselines = [
        ("Majority class",         b0, "Always predict 'disambiguation' (most common class)"),
        ("Rules — blind vocab",    b1, "README §7 keyword list, no model feedback; 0% location recall"),
        ("Rules — corrected vocab",b2, "After 21 vocabulary corrections derived from model review"),
        ("Word 1-2gram + LogReg",  b3, "TF-IDF word unigrams+bigrams on extra_content; n=182 train"),
        ("Char 3-5gram + LogReg",  b4, "TF-IDF char trigrams-5grams on extra_content; n=182 train"),
    ]

    print(f"{'Model':<30} {'Label%':>7} {'Sel%':>7}  "
          f"{'biz':>6} {'loc':>6} {'dis':>6} {'noi':>6}")
    print("─" * 72)

    summary_rows = []
    for name, preds, note in baselines:
        la = accuracy_score(y_test, preds)
        sa = selection_accuracy(preds, y_test)
        pc = per_class_accuracy(preds, y_test)
        print(f"  {name:<28} {la:>6.1%} {sa:>7.1%}  "
              f"{pc.get('business_type', float('nan')):>5.1%} "
              f"{pc.get('location', float('nan')):>6.1%} "
              f"{pc.get('disambiguation', float('nan')):>6.1%} "
              f"{pc.get('noise', float('nan')):>6.1%}")
        summary_rows.append({
            "model": name,
            "label_accuracy":     round(la, 4),
            "selection_accuracy": round(sa, 4),
            "business_type":      round(pc.get("business_type", float("nan")), 4),
            "location":           round(pc.get("location", float("nan")), 4),
            "disambiguation":     round(pc.get("disambiguation", float("nan")), 4),
            "noise":              round(pc.get("noise", float("nan")), 4),
            "parse_errors":       0,
            "notes":              note,
        })

    pd.DataFrame(summary_rows).to_csv(COMPARE_OUT, index=False)
    print(f"\nSaved → {COMPARE_OUT}")

    # ── Per-row comparison CSV ─────────────────────────────────────────────────
    out = test.copy()
    out["rules_blind"]    = b1.values
    out["rules_full"]     = b2.values
    out["ngram_word"]     = b3.values
    out["ngram_char"]     = b4.values

    for col in ["correct_answer", "rules_blind", "rules_full", "ngram_word", "ngram_char"]:
        out[f"sel_{col}"] = out[col].apply(selection_action)

    ref_action = out["sel_correct_answer"]
    for col in ["rules_blind", "rules_full", "ngram_word", "ngram_char"]:
        out[f"sel_correct_{col}"] = (out[f"sel_{col}"] == ref_action).astype(int)

    out["only_rules_correct"] = (
        (out["sel_correct_rules_blind"] == 1) & (out["sel_correct_ngram_word"] == 0)
    ).astype(int)
    out["only_ngram_correct"] = (
        (out["sel_correct_ngram_word"] == 1) & (out["sel_correct_rules_blind"] == 0)
    ).astype(int)

    out.to_csv(ROWS_OUT, index=False)
    print(f"Saved → {ROWS_OUT}")

    # ── Where rules fail that n-grams catch (and vice versa) ──────────────────
    print(f"\nRules-blind unique wins (n-grams wrong): {out['only_rules_correct'].sum()}")
    print(f"N-gram unique wins (rules wrong):         {out['only_ngram_correct'].sum()}")

    # ── Location recall detail (most interesting gap) ─────────────────────────
    loc_mask = y_test == "location"
    print(f"\nLocation recall (n={loc_mask.sum()}):")
    for name, preds, _ in baselines:
        recall = (preds[loc_mask] == "location").mean()
        print(f"  {name:<30} {recall:.1%}")

    print("\nLocation rows that rules-blind misses (no vocabulary can catch these):")
    missed = test[loc_mask & (b1 != "location")]
    for _, r in missed.iterrows():
        print(f"  extra='{r['extra_content']}'  →  '{r['long_name'][:50]}'")


if __name__ == "__main__":
    main()
